---
name: Deploy
on:
  push:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    container: node:20-alpine
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Build the site
        run: pnpm run build
      - name: Install AWS CLI
        run: apk add aws-cli
      - name: Upload files
        run: aws s3 sync ./dist/ s3://${{ secrets.S3_BUCKET_NAME }}
      - name: Invalidate CF cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
